# For full config options, check the docs:
#    docs.serverless.com

service:        student

provider:
    name:       aws
    runtime:    nodejs8.10
    stage:      prod
    region:     eu-central-1
    
    # defines environment variables for connecting to DB
    environment:
        DB_NAME:        ${self:custom.secrets.DB_NAME}
        DB_USER:        ${self:custom.secrets.DB_USER}
        DB_PASSWORD:    ${self:custom.secrets.DB_PASSWORD}
        DB_HOST:        ${self:custom.secrets.DB_HOST}
        DB_PORT:        ${self:custom.secrets.DB_PORT}
        LAMBDA_ENDPOINT:        ${self:custom.secrets.LAMBDA_ENDPOINT}
        LAMBDA_APIKEY:        ${self:custom.secrets.LAMBDA_APIKEY}

#package:
#    individually: true

plugins:
    - serverless-offline
    - serverless-domain-manager

custom:
    # contains the credentials needed to connect to the DB
    secrets:    ${file(secrets.json)}
    customDomain:
        domainName: 'api.emon-teach.com'
        basePath: 'student' # This will be prefixed to all routes
        stage: ${self:provider.stage}
        createRoute53Record: true

#TODO: Implement a more strict CORS policy
functions:
    getStudentByToken:
        handler: src/get.byToken
        description: Get information about a student by their Auth Token.
        events:
            - http:
                path: byToken/{authToken}
                method: get
                cors: true
                request:
                    parameters:
                        paths:
                            authToken: true
    getStudentById:
        handler: src/get.byId
        description: Get information about a student by their ID.
        events:
            - http:
                path: /{studentId}
                method: get
                cors: true
                request:
                    parameters:
                        paths:
                            studentId: true
    getActiveLesson:
        handler: src/get.activeLesson
        description: Get information about a teacher by their Auth Token.
        events:
            - http:
                path: /{studentId}/activeLesson
                method: get
                cors: true
                request:
                    parameters:
                        paths:
                            studentId: true
    deleteStudent:
        handler: src/delete.handler
        description: Delete student with a certain ID.
        events:
            - http:
                path: /{studentId}
                method: delete
                cors: true
                request:
                    parameters:
                        paths:
                            studentId: true
    updateStudent:
        handler: src/update.handler
        description: Update a student's information.
        events:
            - http:
                path: /
                method: put
                cors: true
    addStudent:
        handler: src/create.handler
        description: Create a new student.
        events:
            - http:
                path: /
                method: post
                cors: true
    getEmons:
        handler: src/get.emons
        description: Get blaaaaaaaaaaaaaaa
        events:
            - http:
                path: /{studentId}/emonBalance/byCourse/{courseId}
                method: get
                cors: true
                request:
                    parameters:
                        paths:
                            courseId: true
                            studentId: true
