# For full config options, check the docs:
#    docs.serverless.com

service:        dbFunctions

# contains the credentials needed to connect to the DB
custom:
    secrets:    ${file(secrets.json)}

provider:
    name:       aws
    runtime:    nodejs8.10
    stage:      dev
    region:     eu-central-1
    apiKeys:
        - myApiKey

    # package:
    #     include:
    #         - teacher/**
    #         - student/**
    #         - course/**

    # defines environment variables for connecting to DB
    environment:
        DB_NAME:        ${self:custom.secrets.DB_NAME}
        DB_USER:        ${self:custom.secrets.DB_USER}
        DB_PASSWORD:    ${self:custom.secrets.DB_PASSWORD}
        DB_HOST:        ${self:custom.secrets.DB_HOST}
        DB_PORT:        ${self:custom.secrets.DB_PORT}

functions:
    getTeacherByToken:
        handler: teacher/get.byToken
        description: Get information about a teacher by their Auth Token.
        events:
            - http:
                path: teacher/byToken/{authToken}
                method: get
                private: true
                request:
                    parameters:
                        paths:
                            authToken: true

    getTeacherById:
        handler: teacher/get.byId
        description: Get information about a teacher by their ID.
        events:
            - http:
                path: teacher/{teacherId}
                method: get
                private: true
                request:
                    parameters:
                        paths:
                            teacherId: true
    deleteTeacher:
        handler: teacher/delete.handler
        description: Delete teacher with a certain ID.
        events:
            - http:
                path: teacher/{teacherId}
                method: delete
                private: true
                request:
                    parameters:
                        paths:
                            teacherId: true

    updateTeacher:
        handler: teacher/update.handler
        description: Update a teacher's information.
        events:
            - http:
                path: teacher
                method: put
                private: true

    addTeacher:
        handler: teacher/create.handler
        description: Create a new teacher.
        events:
            - http:
                path: teacher
                method: post
                private: true
